# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docsim < Formula
  desc "Local, in-memory search tool, ranking results by textual similarity."
  homepage "https://github.com/hrs/docsim"
  version "0.1.7"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hrs/docsim/releases/download/v0.1.7/docsim_darwin_arm64.tar.gz"
      sha256 "c849d2aa7312d73e53d6fe453365832fd501e08887197e12b16994745b8059d4"

      def install
        bin.install "docsim"
        man1.install "manpages/docsim.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hrs/docsim/releases/download/v0.1.7/docsim_darwin_x86_64.tar.gz"
      sha256 "8df951de19a774889c16a23dde44c14a7aa71f4cc078ab29a410bf1afa492631"

      def install
        bin.install "docsim"
        man1.install "manpages/docsim.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hrs/docsim/releases/download/v0.1.7/docsim_linux_x86_64.tar.gz"
      sha256 "4707b0f2efb99e04c22a551494c7fd1327446c79d32689597bc613c3252a74aa"

      def install
        bin.install "docsim"
        man1.install "manpages/docsim.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hrs/docsim/releases/download/v0.1.7/docsim_linux_arm64.tar.gz"
      sha256 "ba3f017cb1bb9ddb681dbde4af6362a754e0d810ad85525cfb01352837bba29d"

      def install
        bin.install "docsim"
        man1.install "manpages/docsim.1"
      end
    end
  end

  test do
    system "make test"
  end
end
