# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docsim < Formula
  desc "A local, in-memory search tool, ranking results by textual similarity."
  homepage "https://github.com/hrs/docsim"
  version "0.1.6"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hrs/docsim/releases/download/v0.1.6/docsim_darwin_x86_64.tar.gz"
      sha256 "57e11ce483e073a5d60c98a603726a520de5f2e62ddb30523ff87c5a8370362d"

      def install
        bin.install "docsim"
        man1.install "manpages/docsim.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hrs/docsim/releases/download/v0.1.6/docsim_darwin_arm64.tar.gz"
      sha256 "c15bed9651269753a9660154b227dd055259375f3cbbaa68f9dc5d3d3aa9e546"

      def install
        bin.install "docsim"
        man1.install "manpages/docsim.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hrs/docsim/releases/download/v0.1.6/docsim_linux_arm64.tar.gz"
      sha256 "eff0a6d192a7d4ce02f523630adae084ad3a3dff1e891f97cceb3a8ccd5bb3fe"

      def install
        bin.install "docsim"
        man1.install "manpages/docsim.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hrs/docsim/releases/download/v0.1.6/docsim_linux_x86_64.tar.gz"
      sha256 "849089817c88e2f85f9f8af80278e292a8a56566151cbfccf1f28a40ffe1b73d"

      def install
        bin.install "docsim"
        man1.install "manpages/docsim.1"
      end
    end
  end

  test do
    system "make test"
  end
end
