# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docsim < Formula
  desc "Local, in-memory search tool, ranking results by textual similarity."
  homepage "https://github.com/hrs/docsim"
  version "0.1.7"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hrs/docsim/releases/download/v0.1.7/docsim_0.1.7_darwin_x86_64.tar.gz"
      sha256 "53ca14e6bde4f24b758e1ce5bbf26a65e4f78cd0bd4294ef391c3fa5546987c7"

      def install
        bin.install "docsim"
        man1.install "manpages/docsim.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hrs/docsim/releases/download/v0.1.7/docsim_0.1.7_darwin_arm64.tar.gz"
      sha256 "e9905b34f98c3b58f53a6326bacb99aae2c2a7bdf48652f4c92fffccdc08e031"

      def install
        bin.install "docsim"
        man1.install "manpages/docsim.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hrs/docsim/releases/download/v0.1.7/docsim_0.1.7_linux_x86_64.tar.gz"
      sha256 "ae4f4c76b1494136c579f8946391d08abbda494cc46534033d441ce2e01316f2"

      def install
        bin.install "docsim"
        man1.install "manpages/docsim.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hrs/docsim/releases/download/v0.1.7/docsim_0.1.7_linux_arm64.tar.gz"
      sha256 "438ceb5637cd7378b652152cf726df8cac7633ad1fd79d5b581c34157ac6502b"

      def install
        bin.install "docsim"
        man1.install "manpages/docsim.1"
      end
    end
  end

  test do
    system "make test"
  end
end
